# Site settings
title: ブライダル工房ストレリチア・ソーイングルーム・お花の教室　沖縄名護
description: >  
 一生に一度の思い出に、オリジナルのウェディングドレスを作りませんか？沖縄県名護市にあるウェディングドレスのオーダーメイド・レンタル、ブーケ制作の工房です。長年の洋裁経験とフラワーアレンジメントの経験を継続して、婦人服の仕立て・お直し・リメイクを取り扱う『ソーイングルームくれよん』、『お花の教室美ら花』も営業しております。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://strelitzia-okinawa.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
